accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path('registered/',views.registered,name='registered'),
    path('authenticated/', views.authenticated,name='authenticated'),
    path('register/', views.register, name='register'),

    url(r'^activation/(?P<pk>[0-9]+)/(?P<token>[0-9A-Za-z_\-\.]+)/$',
        views.registration_activation,
        name='registration-activation'),

    path('password-change/', 
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         {'post_change_redirect':'password_change_done'},
         name='password_change'),

    #path('password-change/done/', 
    #     views.PasswordchangeDone,
    #     name='password_change_done')
    
    path('password_change/done/', 
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done')



]

biodiversity/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import re_path, path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from puput import urls as puput_urls

from search import views as search_views

from django.contrib.auth import views as auth_views

import accounts
import data.urls
import polaaar.urls
from . import views

urlpatterns = [
    re_path(r'^django-admin/', admin.site.urls),


    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^accounts/', include('accounts.urls')), 
    url(r'^accounts/', include('django.contrib.auth.urls'), name='accounts'),
   
    # putting api reference in here because it might be generic to the whole site
    url(r'^api_reference/',views.api_reference,name='api_reference'),

    path('data/', include('data.urls')),
    re_path(r'pola3r/', include('polaaar.urls')),
    # re_path(r'users/',include('users.urls')),

    url(r'',include(puput_urls)),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    re_path(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from __future__ import unicode_literals

from django.urls import path
from . import views


app_name = 'data'
urlpatterns = [
   
    path('', views.home, name='home'),
 
]

biodiversity/views.py
from django.shortcuts import render
def api_reference(request):
    return render(request, 'rest_framework/api_reference.html')

biodiversity/templates/_crispy_form.html
{% load crispy_forms_tags %}

{% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}


{% crispy form %}

biodiversity/templates/_form.html
{% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}

{{ form.non_field_errors }}
{% for field in form.hidden_fields %}
{{ field.errors }}
{{ field }}
{% endfor %}

{% for field in form.visible_fields %}
<div class="field">
    {{ field.label_tag }}
    {{ field.errors }}
    {{ field }}
    {{ field.help_text }}
</div>
{% endfor %}

biodiversity/templates/base.html
{% load static wagtailuserbar leaflet_tags menu_tags home_tags %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
            {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
        {% endblock %}
        {% block title_suffix %}
            {% with self.get_site.site_name as site_name %}
                {% if site_name %}- {{ site_name }}{% endif %}
            {% endwith %}
        {% endblock %}
    </title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    {# Global stylesheets #}
    {% leaflet_css plugins="draw" %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.all.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.11/css/mdb.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet"/>

    
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/asRange.min.css' %}">-->

    {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
    {% endblock %}


    <style>
        @media (min-width: 800px) and (max-width: 850px) {
            .navbar:not(.top-nav-collapse) {
                background: #0099CC !important;
            }
        }

        .view, body, html {
            height: 80%
        }

        .navbar {
            background-color: rgba(0, 0, 0, .2)
        }

        .top-nav-collapse {
            background-color: #0099CC;
        }

    </style>


    {% leaflet_js plugins="draw" %}


</head>

<body class="{% block body_class %}{% endblock %}">
{% wagtailuserbar %}

{# HEADER MENU #}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark scrolling-navbar">
    <span><a class="navbar-brand" href="/"><img src="{% static 'logos/logo-biodiversityaq-white.png' %}"
                                                alt="biodiversity.aq logo" height="40"></a></span>
    <!-- Collapsible flat menu content -->
    {% block flat_menu %}
    {% endblock %}

    <!-- Collapsible main menu content -->
    {% main_menu max_levels=3 template="menus/main/level_1.html" %}

    <!-- user menu -->
    <ul id="user-account" class="navbar-nav ml-auto pl-2">
        <li class="nav-item dropdown">
            <a class="dropdown-toggle" href="#" id="userDropdownMenu" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white">
                <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdownMenu">
                {% if user.is_authenticated %}
                    <h5 class="dropdown-header"><strong>Welcome {{ user.username }}</strong></h5>
                    {% if user.is_administrator %}
                        <a class="dropdown-item" href="/admin">Wagtail Admin</a>
                        <a class="dropdown-item" href="/django-admin">Django Admin</a>
                    {% endif %}
                    <a class="dropdown-item"
                       href="{% url 'accounts:password_change' %}">Change password</a>
                    <a class="dropdown-item"
                       href="{% url 'logout' %}?next={{ request.path }}">Log out</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'login' %}?next={{ request.path }}">Log in</a>
                    <a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
            </div>
        </li>
        {% spaceless %}
        {% endspaceless %}
    </ul>
</nav>


{# banner needs to be above flex-wrapper otherwise it won't be displayed #}
{% block banner %}{% endblock %}

{# flex-wrapper is needed to push the footer to the bottom of the page if the content of viewport is <100% height #}
      {# fixed-bottom is not applied on footer because it blocks the content of when scrolls down. Having both #}
      {# fixed-top navbar and fixed-bottom footer is taking too much space on the screen #}
<div class="flex-wrapper">
    {% block content %}{% endblock %}
    {% footer %}
</div>


{# Global javascript #}
<script type="text/javascript" src="{% static 'js/polarrr.js' %}"></script>
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.11/js/mdb.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

<script src='https://unpkg.com/@turf/turf/turf.min.js'></script>    
<!--<script type="text/javascript" src="{% static 'js/jquery-asRange.min.js' %}"></script>-->


<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" type="text/css" href="//wpcc.io/lib/1.0.2/cookieconsent.min.css"/>
<script src="//wpcc.io/lib/1.0.2/cookieconsent.min.js"></script>
<script>window.addEventListener("load", function () {
    window.wpcc.init({
        "border": "normal",
        "colors": {
            "popup": {"background": "#222222", "text": "#ffffff", "border": "#b4eae4"},
            "button": {"background": "#b4eae4", "text": "#000000"}
        },
        "position": "bottom",
        "pushdown": false,
        "fontsize": "large",
        "content": {
            "href": "#",
            "message": "This website uses cookies to ensure that you have the best user experience! By clicking accept, you agree to the terms of the privacy policy",
            "link": "#",
            "button": "Accept"
        }
    })
});</script>
{% block extra_js %}

{% endblock %}
</body>
</html>

biodiversity/templates/footer.html
{% load static %}
<footer>
    <nav class="navbar navbar-expand-lg fixed-bottom">
        <ul class="nav mx-auto">
            <li class="nav-item"><a href="https://www.biodiversity.be/"><img src="{% static 'logos/logo_BBPF_white.png'%}" class="partners-logo"></a></li>
            <li class="nav-item"><a href="http://lifewatch.be/"><img src="{% static 'logos/logo_lifewatch_transp.png'%}" class="partners-logo"></a></li>
            <li class="nav-item"><a href="https://www.scar.org/"><img src="{% static 'logos/SCAR%20logo_white_transp.svg'%}" class="partners-logo"></a></li>
            <li class="nav-item"><a href="http://marinespecies.org/"><img src="{% static 'logos/logo-WORMS-white-background-transp.png'%}" class="partners-logo"></a></li>
            <li class="nav-item"><a href="https://obis.org/"><img src="{% static 'logos/obis_logo_white.svg'%}" class="partners-logo"></a></li>
            <li class="nav-item"><a href="https://www.gbif.org/"><img src="{% static 'logos/GBIF-2015-mark-white.svg'%}" class="partners-logo"></a></li>
            <li class="nav-item"><a href="https://odnature.naturalsciences.be"><img src="{% static 'logos/rbins.png'%}" class="partners-logo"></a></li>
        </ul><!-- end footer-logos container -->
    </nav>
</footer>