data/urls.py
from __future__ import unicode_literals

from django.urls import path
from . import views


app_name = 'data'
urlpatterns = [
   
    path('', views.home, name='home'),
 
]

polaaar/urls.py
from __future__ import unicode_literals
from django.urls import path
from django.conf.urls import include, url
from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'occurrence',views.OccurrenceViewSet,basename='occurrence')
router.register(r'events',views.EventViewSet,basename='events')
router.register(r'eventhierarchy',views.EventHierarchyViewSet,basename='eventhierarchy')
router.register(r'project_metadata',views.ProjectMetadataViewSet,basename='projectmetadata')
router.register(r'sequence',views.SequenceViewSet,basename='sequence')
router.register(r'reference',views.ReferenceViewSet,basename='reference')
router.register(r'geog_location',views.GeogViewSet,basename='geoglocation')
router.register(r'environment',views.EnvironmentViewSet,basename='environment')

### Special routers for sequences and environments
router.register(r'sequences',views.SequencesViewSet,basename='sequences')
router.register(r'environmental_variables',views.EnvironmentVariablesViewSet,basename='environmentalvariables')

app_name = 'polaaar'
urlpatterns = [
   
    url(r'^$', views.home, name='home'),    
    path('search/',views.polaaar_search,name='polaaar_search'),
    path('submit/',views.polaaar_submit,name='polaaar_submit_data'),

    path('envsearch/',views.env_search,name='env_search'),
    url(r'var/',views.env_searched,name='env_searched'),    
    path('seqsearch/',views.seq_search,name='seq_search'),
    path('spatialsearch/',views.spatial_searching,name='spatialsearch'),
    path('spatial_search_table/',views.spatial_search_table,name='spatial_search_table'),

    path('submit_data/',views.email_submission,name='email_submission'),
    path('submit_success/',views.submit_success,name='submit_success'),    

    ###  EXCEL export views
    url(r'^export_projects/',views.export_projects,name='export_projects'),
    url(r'^export_environment/',views.export_environment,name='export_environment'),
    url(r'^export_sequences/',views.export_sequences,name='export_sequences'),
    url(r'^export_events/',views.export_events,name='export_events'),

    ###  View to export raw data files
    path('export_raw_data/',views.GetProjectFiles,name='GetProjectFiles'),

    #### REST API URLS    

    path('',include(router.urls)),
    path('api-auth/',include('rest_framework.urls',namespace='rest_framework'))
 
]

polaaar/forms.py
from .models import MailFile
from django import forms

class EmailForm(forms.ModelForm):
  email = forms.EmailField(max_length=200,widget=forms.TextInput(attrs={'class': "form-control",'id': "clientemail"}))
  message = forms.CharField( widget=forms.Textarea(attrs={'class': "form-control"}))
  subject = forms.CharField( widget=forms.TextInput(attrs={'class': "form-control"}))
  class Meta:
    model = MailFile
    fields = ('email','subject','message','document',)
  

polaaar/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.http import HttpResponsePermanentRedirect, HttpResponse, JsonResponse, HttpResponseNotFound  
from django.db.models import Prefetch, Q
from django.contrib.gis.db.models.functions import AsGeoJSON, Centroid 
from django.core.files.storage import FileSystemStorage
from .forms import EmailForm
from django.core.mail import send_mail, EmailMessage
from django.core.serializers import serialize
from django_filters.rest_framework import DjangoFilterBackend

from polaaar.models import *
from accounts.models import UserProfile

from rest_framework import viewsets, filters
from rest_framework import permissions
from polaaar.serializers import *

import xlsxwriter, io, datetime, zipfile, os


def home(request):
    qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT')))
    return render(request, 'polaaar_home.html',{'qs_results':qs_results})


#########################################################
### DJANGO Search views
##########  

def polaaar_search(request):

    user = request.user    

    #### This is used to generate the links back to the project search page. If there is a ?pid search string 
    #### Then the user is directed to the project search page with data filtered by that specific project.

    if len(request.GET.get('pid','')):
        proj = request.GET.get('pid','')

        if user.is_authenticated and user.is_superuser:
            qs = ProjectMetadata.objects.filter(id=proj)

            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(id=proj)

        elif user.is_authenticated:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)|Q(
                project_creator__username=user.username)).filter(id=proj).prefetch_related('event_hierarchy')

            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)|Q(
                    event_hierarchy__project_metadata__project_creator__username = user.username))
        else:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)).filter(id=proj).prefetch_related('event_hierarchy')

            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True))
        buttondisplay = "Display events"
        ## This triggers a refresh button to appear in the project search tool if the user is looking at filtered project data
        viewprojs = True

    else:
    
        if user.is_authenticated and user.is_superuser:
            qs = ProjectMetadata.objects.all()
            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).all()
        elif user.is_authenticated:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)|Q(
                project_creator__username=user.username)).prefetch_related('event_hierarchy')
            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)|Q(
                    event_hierarchy__project_metadata__project_creator__username = user.username))
        else:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)).prefetch_related('event_hierarchy')
            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True))
        buttondisplay = "Refresh map"
        viewprojs = False
    return render(request, 'polaaar_search.html',{'qs_results':qs_results,'qs':qs, 'buttondisplay':buttondisplay, 'viewprojs':viewprojs})


def env_search(request):    
    qs = Variable.objects.all()       
    return render(request, 'polaaarsearch/environment.html',{'qs':qs})



def env_searched(request):
    user = request.user
    if request.method=='GET':
        var = request.GET.get('var','')
        vars = var.split(',')
        
        #vartype = request.GET.get('vartype','')
        if user.is_authenticated and user.is_superuser:

            qsenv = Environment.objects.filter(env_variable__name__in = vars)

        elif user.is_authenticated:		

            qsenv = Environment.objects.filter(env_variable__name__in = vars).filter(
            Q(event__event_hierarchy__project_metadata__is_public=True)|Q(
                event__event_hierarchy__project_metadata__project_creator__username = user.username))

        else:

            qsenv = Environment.objects.filter(env_variable__name__in = vars).filter(
            Q(event__event_hierarchy__project_metadata__is_public=True))
        
        Y = qsenv.values_list('env_variable__var_type')
        

        try:
            x = list(Y).index(('NUM',))
            x = True
        except:
            x = False


        return render(request,'polaaarsearch/env_searched.html',{'qsenv':qsenv,'test':x})#,'vartype':vartype





def seq_search(request):
    user = request.user
    if user.is_authenticated and user.is_superuser:
        qs = Sequences.objects.all().select_related()
    elif user.is_authenticated:
        qs = Sequences.objects.filter(
            Q(event__event_hierarchy__project_metadata__is_public=True)|Q(
                event__event_hierarchy__project_metadata__project_creator__username = user.username)).select_related()
    else:
        qs = Sequences.objects.filter(
            Q(event__event_hierarchy__project_metadata__is_public=True)).select_related()
    return render(request, 'polaaarsearch/sequences.html',{'qs':qs})


def spatial_searching(request):
    user = request.user
    if user.is_authenticated and user.is_superuser:
        qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).all().select_related()
    if user.is_authenticated:
        qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
            Q(event_hierarchy__project_metadata__is_public=True)|Q(event_hierarchy__project_metadata__project_creator__username = user.username))
    else:
        qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
            Q(event_hierarchy__project_metadata__is_public=True))
    return render(request, 'polaaarsearch/spatial_search.html',{'qs_results':qs_results})


def spatial_search_table(request):
    user = request.user
    if request.method== "GET":
        IDS = request.GET.getlist('id')        
        IDS = IDS[0].split(',')  
        if user.is_authenticated and user.is_superuser:
            qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(pk__in=IDS).select_related()
        if user.is_authenticated:
            qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)|Q(
                    event_hierarchy__project_metadata__project_creator__username = user.username)).filter(pk__in=IDS)
        else:
            qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)).filter(pk__in=IDS)

    return render(request, 'polaaarsearch/spatial_search_table.html',{'qs_results':qs_results})


#########################################################
### Download project files

def GetProjectFiles(request):
    # Files (local path) to put in the .zip
    # FIXME: Change this (get paths from DB etc)
    if request.method == "GET":
        idval = request.GET.get('id')

        pf = ProjectFiles.objects.filter(project__id=idval)
        filenames = [x.files.path for x in pf]
        pfnm = ProjectMetadata.objects.filter(id=idval).values_list('project_name')[0][0]

        # Folder name in ZIP archive which contains the above files
        # E.g [thearchive.zip]/somefiles/file2.txt
        # FIXME: Set this to something better
        zip_subdir = "%s_raw_files" % pfnm
        zip_filename = "%s.zip" % zip_subdir

        # Open StringIO to grab in-memory ZIP contents
        s = io.BytesIO()

        # The zip compressor
        zf = zipfile.ZipFile(s, "w")

        for fpath in filenames:
            # Calculate path for file in zip
            fdir, fname = os.path.split(fpath)
            zip_path = os.path.join(zip_subdir, fname)

            # Add file, at correct path
            zf.write(fpath, zip_path)

        # Must close zip for all contents to be written
        zf.close()

        # Grab ZIP file from in-memory, make response with correct MIME-type
        resp = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
        # ..and correct content-disposition
        resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

        return resp




#########################################################
### Submit views
def polaaar_submit(request):
    return render(request, 'polaaar_submit.html')

#######################################################
##### 
### Email submission views

def email_submission(request):

    usr = request.user
    if usr.is_authenticated:
        init = {'email':usr.email}
    else:
        init = {'email':''}
    if request.method == "POST":
       
        form = EmailForm(request.POST,request.FILES,initial=init)
        if form.is_valid():
            post = form.save(commit=False)
            #post.published_date = timezone.now()
            post.save()

polaaar/templates/polaaar_home.html
{% extends "base.html" %}
{% load static leaflet_tags geojson_tags %}

{% block title %}
POLA3R
{% endblock title %}


{% block body_class %}{% endblock %}

{% block extra_css %}
{% leaflet_css %}

{% endblock extra_css %}

{% block content %}

<div class="container-fluid" id="polaaar_bkgd"
     style="background-image: url({% static 'imgs/img1.png' %});background-size:cover;background-repeat:no-repeat;padding-bottom:20px;">
    <div class="row" style="border-bottom-width:0px;">
        <div class="col-12" style="text-align:center">
            <img style="border-radius:15px" width="25%" class="fadeinclass" src="{% static 'logos/polaaar_logo.png' %}" />
        </div>
    </div>

    <div class="row justify-content-md-center" style="border-width:0px;">
        <div class="col-12 col-lg-5 fadeinclass" style="float:right;">

            {% leaflet_map "landing_map" callback="window.map_init"  %}

            <!--<p>
        Pola<sub>3</sub>r is an information system dedicated to facilitate the discovery, access and analysis of molecular
        microbial diversity (meta)data generated by Antarctic researchers.

        This includes the ability to upload information that describes (i) a research project that involves
        molecular microbial diversity sequence information (this goes into the Integrated Publishing Toolkit
        system that was developed by GBIF), (ii) communicating descriptive environmental information through a
        relatively newly accepted standard set of terms (Genomic Standards Consortium, MiMARKS), (iii) uploading
        links to DNA, RNA, proteomic or metabolomic data sets that have been deposited in public repositories, and
        the required metadata describing them.
    </p>-->
            <p style="font-size:10pt;color:white">Map attribution: Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012</p>
        </div>
        <div class="col-12 col-lg-3 fadeinclass">
            <div style="background-color:rgba(255,255,255,0.75);border-radius:15px;padding-bottom:5px;padding-right:12px; padding-top:5px;">
                <a role="button" href="{% url 'polaaar:polaaar_search' %}" class="btn btn-biodiversity-lightblue btn-lg waves-effect" style="width:100%">
                Search the database <i class="fas fa-search pl-1"></i>
                </a>
                <a role="button" href="http://share.biodiversity.aq/MARS/Vision/mARSVision.pdf" class="btn btn-biodiversity-lightblue btn-lg" style="width:100%">
                    Read the vision paper <i class="fas fa-book-reader pl-1"></i>
                </a>
            {% if user.is_authenticated %}
                <a role="button" href="{% url 'polaaar:polaaar_submit_data' %}" class="btn btn-biodiversity-lightblue btn-lg" style="width:100%">
                    Submit a dataset <i class="fas fa-cloud-upload-alt pl-1"></i>
                </a>
            {% endif %}    
            </div>
            
            {% if user.is_authenticated %}
            {% else %}
            <div style="background-color:rgba(255,255,255,0.75);border-radius:15px;margin-top:5px;padding-bottom:5px;padding-right:12px">
                <p style="font-size:18pt">To submit data:</p>
                <a role="button" href="{% url 'login' %}?next={{request.path}}" class="btn btn-biodiversity-teal btn-lg" style="width:100%">
                    Login <i class="fas fa-user pl-1"></i>
                </a>
                <a role="button" href="/accounts/register" class="btn btn-biodiversity-teal btn-lg" style="width:100%">
                    Register <i class="fas fa-user-plus pl-1"></i>
                </a>
            </div>
            {% endif %}
        </div>
    </div>

</div>

<div class="container">
    <div class="row justify-content-md-center" style="border-width:0px;">
        <div class="col-12">
            <h1>Welcome</h1>
            <p>
                Pola<sub>3</sub>r is an information system dedicated to facilitate the discovery, access and analysis of molecular
                microbial diversity (meta)data generated by Antarctic researchers.

                This includes the ability to upload information that describes (i) a research project that involves
                molecular microbial diversity sequence information (this goes into the Integrated Publishing Toolkit
                system that was developed by GBIF), (ii) communicating descriptive environmental information through a
                relatively newly accepted standard set of terms (Genomic Standards Consortium, MiMARKS), (iii) uploading
                links to DNA, RNA, proteomic or metabolomic data sets that have been deposited in public repositories, and
                the required metadata describing them.
            </p>            
        </div>
    </div>



</div>

{% block extra_js %}

<style>

    .leaflet-container { /* all maps */
        width: 100%;
        height: 400px;
        -webkit-box-shadow: 10px 10px 42px 0px rgba(0,0,0,0.75);
        -moz-box-shadow: 10px 10px 42px 0px rgba(0,0,0,0.75);
        box-shadow: 10px 10px 42px 0px rgba(0,0,0,0.75);
    }

    #specialbigmap {
        height: 800px;
    }

    /* Resize the "display_raw" textbox */
    .django-leaflet-raw-textarea {
        width: 100%;
    }

    .leaflet-control-attribution{
        display:none;
    }
</style>

<script type="text/javascript">
    var collection = {{ qs_results|geojsonfeature|safe }};    

    function map_init(map, options) {
        var geojsonMarkerOptions = {
            radius: 3,
            fillColor: "#ff7800",
            color: "#000",
            weight: 1,
            opacity: 1,
            fillOpacity: 0.8
        };

        L.geoJson(collection,{
            pointToLayer: function(feature,latlng){
                return L.circleMarker(latlng,geojsonMarkerOptions);
            }
        }).addTo(map);

        map.attributionControl.removeAttribution()

         L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {
                    attribution: ''
                }).addTo(map);

      }


    


</script>

{% endblock extra_js %}


{% endblock content %}

polaaar/templates/polaaar_submit.html
{% extends "base.html" %}
{% load static leaflet_tags %}

{% block title %}
POLA3R search
{% endblock title %}


{% block body_class %}{% endblock %}

{% block extra_css %}
{% leaflet_css %}

{% endblock extra_css %}

{% block content %}

        {% if user.is_authenticated %}
<div class="container-fluid">
    <div class="row justify-content-center" style="padding-top:20px;padding-bottom:160px; border-width:0px;">

        <div class="col-12" style="text-align:center">
            <h1>Do you have some data to submit?</h1>
        </div>

        <div class="col-12 text-center" style="text-align:center">

            <a href="#"><img style="background-color:white;border:solid black 2px;border-radius:100px" src="{% static 'imgs/dna_clipart.png' %}" /></a>

            <h2>Submit data to POLA<sub>3</sub>R <i class="fas fa-dna pl-1"></i></h2>

            <a role="button" href="https://press3.mcs.anl.gov/gensc/mixs/" class="btn btn-biodiversity-lightblue btn-lg" style="width:30%;display:inline-block">
                MIxS instructions
            </a>
            <a role="button" href="{% static 'files/Template_SeqDataPolaaar_v1.xlsx' %}" class="btn btn-biodiversity-lightblue btn-lg" style="width:30%;display:inline-block;">
                Download the datasheet
            </a>

        </div>
        <div class="col-12">
            <hr />
        </div>
        <div class="col-12 col-md-8" style="text-align:left">

            <h4>1) Click the above button to download the xlsx sheet</h4>
            <h4>2) Read all the instructions in the ReadMe tab of the spreadsheet</h4>
            <h4>3) Fill in the <span style="color:darkorange">dark orange cells</span> at minimum</h4>
            <h4>4) Create a record for your dataset in <a href="https://ipt.biodiversity.aq/">IPT</a></h4>
            <h4>
                5) Once completed, <a href="/pola3r/submit_data">Click here</a> to submit your datasheet
                <strong>(N.B. Your data sheet will be reviewed before data become available online)</strong>
            </h4>
        </div>
        <div class="col-12 col-md-5 text-center">

            <a role="button" href="/pola3r/submit_data" class="btn btn-biodiversity-teal btn-lg">Submit data</a>

        </div>
        <div class="col-12">
            <hr />
        </div>
        <div class="col-12 col-md-7" style="text-align:left">
            <h3>Do you have a dataset, but aren't sure where to put it?</h3>
            <h3><a href="/pola3r/submit_data">Submit your datasheet</a> to the portal and we will review it</h3>
        </div>

               
    </div>

</div>



{% else %}
<div class="row" style="padding-top:20px; border-width:0px;">
    <div class="col-12">
        <h1> Sorry, you must be <a href="{% url 'login' %}?next={{request.path}}">Logged In</a> to view this page</h1>
    </div>
    {% endif %}

</div>


{% block extra_js %}





{% endblock extra_js %}



{% endblock content %}