data/urls.py
from __future__ import unicode_literals

from django.urls import path
from . import views


app_name = 'data'
urlpatterns = [
   
    path('', views.home, name='home'),
 
]

polaaar/urls.py
from __future__ import unicode_literals
from django.urls import path
from django.conf.urls import include, url
from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'occurrence',views.OccurrenceViewSet,basename='occurrence')
router.register(r'events',views.EventViewSet,basename='events')
router.register(r'eventhierarchy',views.EventHierarchyViewSet,basename='eventhierarchy')
router.register(r'project_metadata',views.ProjectMetadataViewSet,basename='projectmetadata')
router.register(r'sequence',views.SequenceViewSet,basename='sequence')
router.register(r'reference',views.ReferenceViewSet,basename='reference')
router.register(r'geog_location',views.GeogViewSet,basename='geoglocation')
router.register(r'environment',views.EnvironmentViewSet,basename='environment')

### Special routers for sequences and environments
router.register(r'sequences',views.SequencesViewSet,basename='sequences')
router.register(r'environmental_variables',views.EnvironmentVariablesViewSet,basename='environmentalvariables')

app_name = 'polaaar'
urlpatterns = [
   
    url(r'^$', views.home, name='home'),    
    path('search/',views.polaaar_search,name='polaaar_search'),
    path('submit/',views.polaaar_submit,name='polaaar_submit_data'),

    path('envsearch/',views.env_search,name='env_search'),
    url(r'var/',views.env_searched,name='env_searched'),    
    path('seqsearch/',views.seq_search,name='seq_search'),
    path('spatialsearch/',views.spatial_searching,name='spatialsearch'),
    path('spatial_search_table/',views.spatial_search_table,name='spatial_search_table'),

    path('submit_data/',views.email_submission,name='email_submission'),
    path('submit_success/',views.submit_success,name='submit_success'),    

    ###  EXCEL export views
    url(r'^export_projects/',views.export_projects,name='export_projects'),
    url(r'^export_environment/',views.export_environment,name='export_environment'),
    url(r'^export_sequences/',views.export_sequences,name='export_sequences'),
    url(r'^export_events/',views.export_events,name='export_events'),

    ###  View to export raw data files
    path('export_raw_data/',views.GetProjectFiles,name='GetProjectFiles'),

    #### REST API URLS    

    path('',include(router.urls)),
    path('api-auth/',include('rest_framework.urls',namespace='rest_framework'))
 
]

polaaar/forms.py
from .models import MailFile
from django import forms

class EmailForm(forms.ModelForm):
  email = forms.EmailField(max_length=200,widget=forms.TextInput(attrs={'class': "form-control",'id': "clientemail"}))
  message = forms.CharField( widget=forms.Textarea(attrs={'class': "form-control"}))
  subject = forms.CharField( widget=forms.TextInput(attrs={'class': "form-control"}))
  class Meta:
    model = MailFile
    fields = ('email','subject','message','document',)
  

polaaar/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.http import HttpResponsePermanentRedirect, HttpResponse, JsonResponse, HttpResponseNotFound  
from django.db.models import Prefetch, Q
from django.contrib.gis.db.models.functions import AsGeoJSON, Centroid 
from django.core.files.storage import FileSystemStorage
from .forms import EmailForm
from django.core.mail import send_mail, EmailMessage
from django.core.serializers import serialize
from django_filters.rest_framework import DjangoFilterBackend

from polaaar.models import *
from accounts.models import UserProfile

from rest_framework import viewsets, filters
from rest_framework import permissions
from polaaar.serializers import *

import xlsxwriter, io, datetime, zipfile, os


def home(request):
    qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT')))
    return render(request, 'polaaar_home.html',{'qs_results':qs_results})


#########################################################
### DJANGO Search views
##########  

def polaaar_search(request):

    user = request.user    

    #### This is used to generate the links back to the project search page. If there is a ?pid search string 
    #### Then the user is directed to the project search page with data filtered by that specific project.

    if len(request.GET.get('pid','')):
        proj = request.GET.get('pid','')

        if user.is_authenticated and user.is_superuser:
            qs = ProjectMetadata.objects.filter(id=proj)

            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(id=proj)

        elif user.is_authenticated:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)|Q(
                project_creator__username=user.username)).filter(id=proj).prefetch_related('event_hierarchy')

            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)|Q(
                    event_hierarchy__project_metadata__project_creator__username = user.username))
        else:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)).filter(id=proj).prefetch_related('event_hierarchy')

            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True))
        buttondisplay = "Display events"
        ## This triggers a refresh button to appear in the project search tool if the user is looking at filtered project data
        viewprojs = True

    else:
    
        if user.is_authenticated and user.is_superuser:
            qs = ProjectMetadata.objects.all()
            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).all()
        elif user.is_authenticated:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)|Q(
                project_creator__username=user.username)).prefetch_related('event_hierarchy')
            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)|Q(
                    event_hierarchy__project_metadata__project_creator__username = user.username))
        else:
            qs = ProjectMetadata.objects.filter(Q(is_public=True)).prefetch_related('event_hierarchy')
            qs_results = Event.objects.annotate(
            geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True))
        buttondisplay = "Refresh map"
        viewprojs = False
    return render(request, 'polaaar_search.html',{'qs_results':qs_results,'qs':qs, 'buttondisplay':buttondisplay, 'viewprojs':viewprojs})


def env_search(request):    
    qs = Variable.objects.all()       
    return render(request, 'polaaarsearch/environment.html',{'qs':qs})



def env_searched(request):
    user = request.user
    if request.method=='GET':
        var = request.GET.get('var','')
        vars = var.split(',')
        
        #vartype = request.GET.get('vartype','')
        if user.is_authenticated and user.is_superuser:

            qsenv = Environment.objects.filter(env_variable__name__in = vars)

        elif user.is_authenticated:		

            qsenv = Environment.objects.filter(env_variable__name__in = vars).filter(
            Q(event__event_hierarchy__project_metadata__is_public=True)|Q(
                event__event_hierarchy__project_metadata__project_creator__username = user.username))

        else:

            qsenv = Environment.objects.filter(env_variable__name__in = vars).filter(
            Q(event__event_hierarchy__project_metadata__is_public=True))
        
        Y = qsenv.values_list('env_variable__var_type')
        

        try:
            x = list(Y).index(('NUM',))
            x = True
        except:
            x = False


        return render(request,'polaaarsearch/env_searched.html',{'qsenv':qsenv,'test':x})#,'vartype':vartype





def seq_search(request):
    user = request.user
    if user.is_authenticated and user.is_superuser:
        qs = Sequences.objects.all().select_related()
    elif user.is_authenticated:
        qs = Sequences.objects.filter(
            Q(event__event_hierarchy__project_metadata__is_public=True)|Q(
                event__event_hierarchy__project_metadata__project_creator__username = user.username)).select_related()
    else:
        qs = Sequences.objects.filter(
            Q(event__event_hierarchy__project_metadata__is_public=True)).select_related()
    return render(request, 'polaaarsearch/sequences.html',{'qs':qs})


def spatial_searching(request):
    user = request.user
    if user.is_authenticated and user.is_superuser:
        qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).all().select_related()
    if user.is_authenticated:
        qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
            Q(event_hierarchy__project_metadata__is_public=True)|Q(event_hierarchy__project_metadata__project_creator__username = user.username))
    else:
        qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
            Q(event_hierarchy__project_metadata__is_public=True))
    return render(request, 'polaaarsearch/spatial_search.html',{'qs_results':qs_results})


def spatial_search_table(request):
    user = request.user
    if request.method== "GET":
        IDS = request.GET.getlist('id')        
        IDS = IDS[0].split(',')  
        if user.is_authenticated and user.is_superuser:
            qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(pk__in=IDS).select_related()
        if user.is_authenticated:
            qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)|Q(
                    event_hierarchy__project_metadata__project_creator__username = user.username)).filter(pk__in=IDS)
        else:
            qs_results = Event.objects.annotate(geom=AsGeoJSON(Centroid('footprintWKT'))).filter(
                Q(event_hierarchy__project_metadata__is_public=True)).filter(pk__in=IDS)

    return render(request, 'polaaarsearch/spatial_search_table.html',{'qs_results':qs_results})


#########################################################
### Download project files

def GetProjectFiles(request):
    # Files (local path) to put in the .zip
    # FIXME: Change this (get paths from DB etc)
    if request.method == "GET":
        idval = request.GET.get('id')

        pf = ProjectFiles.objects.filter(project__id=idval)
        filenames = [x.files.path for x in pf]
        pfnm = ProjectMetadata.objects.filter(id=idval).values_list('project_name')[0][0]

        # Folder name in ZIP archive which contains the above files
        # E.g [thearchive.zip]/somefiles/file2.txt
        # FIXME: Set this to something better
        zip_subdir = "%s_raw_files" % pfnm
        zip_filename = "%s.zip" % zip_subdir

        # Open StringIO to grab in-memory ZIP contents
        s = io.BytesIO()

        # The zip compressor
        zf = zipfile.ZipFile(s, "w")

        for fpath in filenames:
            # Calculate path for file in zip
            fdir, fname = os.path.split(fpath)
            zip_path = os.path.join(zip_subdir, fname)

            # Add file, at correct path
            zf.write(fpath, zip_path)

        # Must close zip for all contents to be written
        zf.close()

        # Grab ZIP file from in-memory, make response with correct MIME-type
        resp = HttpResponse(s.getvalue(), content_type = "application/x-zip-compressed")
        # ..and correct content-disposition
        resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

        return resp




#########################################################
### Submit views
def polaaar_submit(request):
    return render(request, 'polaaar_submit.html')

#######################################################
##### 
### Email submission views

def email_submission(request):

    usr = request.user
    if usr.is_authenticated:
        init = {'email':usr.email}
    else:
        init = {'email':''}
    if request.method == "POST":
       
        form = EmailForm(request.POST,request.FILES,initial=init)
        if form.is_valid():
            post = form.save(commit=False)
            #post.published_date = timezone.now()
            post.save()

polaaar/templates/polaaarsubmit/email_submission.html
{% extends "base.html" %}
{% load static leaflet_tags %}

{% block title %}
POLA3R
{% endblock title %}


{% block body_class %}{% endblock %}

{% block extra_css %}
{% leaflet_css %}

{% endblock extra_css %}

{% block content %}
<div class="container" style="padding-top:60px;">


    {% if user.is_authenticated %}

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" class="post-form form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                <h3 style="margin-bottom: 20px;color:#a3b745 ">Submit data to POLA<sub>3</sub>R</h3>
                <div class="form-group">
                    {{ form.email.errors }}
                    <label class="control-label col-md-12" for="{{ form.email.id_for_label }}">Your email</label>
                    <div class="col-md-12">{{ form.email }}</div>
                    <div class="clear"></div>
                </div>
                <div class="form-group">
                    {{ form.subject.errors }}
                    <label class="control-label col-12" for="{{ form.subject.id_for_label }}">Data set name</label>
                    <div class="col-12">{{ form.subject }}</div>
                    <div class="clear"></div>
                </div>
                <div class="form-group">
                    {{ form.document.errors }}
                    <label class="control-label col-12" for="{{ form.document.id_for_label }}">Select data sheet</label>
                    <div class="col-12">{{ form.document }}</div>
                    <div class="clear"></div>
                </div>
                <div class="form-group">
                    {{ form.message.errors }}
                    <label class="control-label col-12" for="{{ form.message.id_for_label }}">Additional information</label>
                    <div class="col-12">{{ form.message}}</div>
                    <div class="clear"></div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2"></label>
                    <div class="col-8"><input class="btn btn-biodiversity-teal btn-lg" type="submit" name="submit" value="Submit data"></div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
        <div class="col-12 col-md-6">
            <h3 style="margin-bottom: 20px;color:#a3b745 ">POLA<sub>3</sub>R submission checklist</h3>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> Have you downloaded the
                <a href="{% static 'files/Template_SeqDataPolaaar_v1.xlsx' %}">data sheet</a>?
            </h4>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> Have you filled in the
                dark orange cells in the data sheet as a minimum?
            </h4>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> Have you checked your data sheet
                to make sure no sensitive or confidential information has been accidentally included?
            </h4>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> Have you made a record for your dataset
                in the <a href="https://ipt.biodiversity.aq">IPT</a>?
            </h4>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> Have you stored a local version of your data sheet
                somewhere you can easily find it again?
            </h4>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> Make sure to include your correct e-mail address
                so we can make sure to get a hold of you with questions.
            </h4>
            <h4>
                <i class="far fa-check-square" style="color:green"></i> If submitting a dataset you're unsure about, please
                give us as much information in the "additional information" section as possible.
            </h4>



        </div>
    </div>

    {% else %}
    <div class="row">
        <div class="col-12">
            <h3 style="text-align:center;margin-bottom: 20px;color:#a3b745 ">Sorry you must be signed in to POLA<sub>3</sub>R to submit</h3>
        </div>
    </div>

    {% endif %}

</div>
{% block extra_js %}





{% endblock extra_js %}



{% endblock content %}

polaaar/templates/polaaarsubmit/submit_success.html
{% extends "base.html" %}
{% load static leaflet_tags %}

{% block title %}
POLA3R search
{% endblock title %}


{% block body_class %}{% endblock %}

{% block extra_css %}
{% leaflet_css %}
<style>
    body {
        padding-top: 60px;
    }

    @media (min-width: 800px) and (max-width: 850px) {
        .navbar:not(.top-nav-collapse) {
            background: #0099CC !important;
        }
    }

    .view, body, html {
        height: 80%
    }

    .navbar {
        background-color: rgba(0, 0, 0, .2)
    }

    .top-nav-collapse {
        background-color: #0099CC;
    }
</style>
{% endblock extra_css %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center" style="padding-top:20px;padding-bottom:160px; border-width:0px;">

        <div class="col-12 text-center" style="text-align:center">

            <a href="#"><img style="background-color:white;border:solid black 2px;border-radius:100px" src="{% static 'imgs/dna_clipart.png' %}" /></a>

            <h2>Thanks for submitting data to POLA<sub>3</sub>R <i class="fas fa-dna pl-1"></i></h2>
            
        </div>
        <div class="col-4">
            <a role="button" href="{% url 'polaaar:polaaar_search' %}" class="btn btn-primary btn-lg" style="width:100%">
                Explore POLA<sub>3</sub>R <i class="fas fa-binoculars pl-1"></i>
            </a>
            <a role="button" href="{% url 'polaaar:home' %}" class="btn btn-primary btn-lg" style="width:100%">
                Return home <i class="fas fa-home pl-1"></i>
            </a>
        </div>
    </div>

</div>


{% block extra_js %}





{% endblock extra_js %}



{% endblock content %}